# Generated by Django 3.0.7 on 2020-07-07 03:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2020, 7, 7, 3, 43, 4, 525881))),
                ('start_date', models.DateTimeField(default=datetime.datetime(2020, 7, 7, 3, 43, 4, 525897))),
                ('end_date', models.DateTimeField(default=datetime.datetime(2020, 7, 7, 3, 43, 4, 525907))),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='core.Question')),
            ],
        ),
    ]
