# Generated by Django 3.0.7 on 2020-07-07 21:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 7, 21, 59, 16, 394894)),
        ),
        migrations.AlterField(
            model_name='question',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 7, 21, 59, 16, 394920)),
        ),
        migrations.AlterField(
            model_name='question',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 7, 21, 59, 16, 394910)),
        ),
    ]
